version: "3.6"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - appdb:/var/lib/mysql
volumes:
  appdb:
